import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import HelpPopup from "../components/HelpPopup";
import OlimpiadasModal from "@/components/OlimpiadasModal";
import { AtletasProvider } from "@/context/AtletasContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AtletasProvider>
          <Navbar />
          {children}
          {<HelpPopup />}
          {<OlimpiadasModal />}
        </AtletasProvider>
      </body>
    </html>
  );
}
